# Generated by Django 2.0.2 on 2018-08-15 14:41
import shortuuid

from django.db import migrations
import shortuuidfield.fields


def add_shortuuid_to_previous_users(apps, schema_editor):
    User = apps.get_model('accounts', 'User')
    for user in User.objects.all():
        user.uid = shortuuid.uuid()
        user.save(update_fields=['uid'])


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='uid',
            field=shortuuidfield.fields.ShortUUIDField(blank=True, editable=False, max_length=22),
        ),
        migrations.RunPython(add_shortuuid_to_previous_users,
                             reverse_code=migrations.RunPython.noop)
    ]
