# Generated by Django 2.0.2 on 2018-08-15 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20180815_1441'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.URLField(default='default_avatar.jpg'),
        ),
    ]
